# Generated by Django 4.1.4 on 2022-12-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testset',
            name='slug',
            field=models.CharField(auto_created=True, default=None, max_length=120),
        ),
    ]
